"""Section 16 performance targets (milestone M9), measured.

    python -m bench.perf            # print
    python -m bench.perf --write    # also append to bench/results.md
"""
import argparse
import random
import time
from pathlib import Path

from bench.generators import random_grid, real_boards
from weaveengine.plan.context import Options
from weaveengine.router import route_board
from weaveengine.topo import kernel, planar_map
from weaveengine.topo.search import route
from weaveengine.topo.state import TopoState


def measure() -> list[tuple[str, str, str, str]]:
    rows = []
    # 1. Triangulation and table build for about 5,000 pads: a few seconds.
    board = random_grid(71, 71, nets=0, seed=1)
    t = time.perf_counter()
    pmap = planar_map.build(board)
    build = time.perf_counter() - t
    rows.append(("map build, %d pads (%d triangles)" % (len(board.pads), pmap.num_triangles), "a few seconds",
                 f"{build:.2f} s", "met" if build < 5 else "MISSED"))

    # 2. A single search on a mid-size board: low milliseconds on average.
    board = random_grid(30, 30, nets=0, seed=2)
    pmap = planar_map.build(board)
    state = TopoState(pmap)
    rng = random.Random(3)
    pads = sorted(pmap.pad_edges)
    route(pmap, state, pads[0], pads[1])  # compile / warm up
    spent, count, wire = 0.0, 0, 0
    for _ in range(600):
        a, b = rng.sample(pads, 2)
        t = time.perf_counter()
        r = route(pmap, state, a, b)
        spent += time.perf_counter() - t
        count += 1
        if r is not None and len(state.wire_path) < 250:
            wire += 1
            state.insert(wire, r.steps)
    rows.append(("search, %d pads, %d wires in place (%s kernel)" % (len(board.pads), len(state.wire_path),
                 "compiled" if kernel.AVAILABLE else "Python"), "low milliseconds", f"{1000 * spent / count:.2f} ms", 
                 "met" if spent / count < 0.01 else "MISSED"))

    # 3. Phase 3 converges in tens of rounds, not hundreds; and end-to-end times on the real boards.
    for name, board in real_boards().items():
        t = time.perf_counter()
        result = route_board(board, options=Options(portfolio=1))
        s = result.stats
        rows.append((f"rip-up rounds, {name}", "tens, not hundreds", str(s["ripup_rounds"]), "met" if s["ripup_rounds"] < 100 else "MISSED"))
        rows.append((f"end to end, {name}, single variant", "-", f"{time.perf_counter() - t:.1f} s ({s['routed']}/{s['connections']}, {s['vias']} vias)", "-"))
        t = time.perf_counter()
        result = route_board(board)
        s = result.stats
        rows.append((f"end to end, {name}, raced variants", "-", f"{time.perf_counter() - t:.1f} s ({s['routed']}/{s['connections']}, {s['vias']} vias)", "-"))
    return rows


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()
    lines = ["| measurement | target (section 16) | measured | |", "|---|---|---|---|"]
    lines += [f"| {a} | {b} | {c} | {d} |" for a, b, c, d in measure()]
    print("\n".join(lines))
    if args.write:
        path = Path(__file__).with_name("results.md")
        text = path.read_text() if path.exists() else "# Benchmark results\n"
        marker = "\n## Performance targets (M9)\n"
        text = text.split(marker)[0].rstrip() + "\n" + marker + "\nGenerated by `python -m bench.perf --write`.\n\n" + "\n".join(lines) + "\n"
        path.write_text(text)


if __name__ == "__main__":
    main()
