"""Benchmark runner: records the section 1 metrics for each board and configuration.

    python -m bench.run                 # full pipeline on every board
    python -m bench.run --experiments   # the section 17.3 comparisons (E1 - E5)
    python -m bench.run --write         # also write bench/results.md
"""
import argparse
import resource
import sys
from pathlib import Path

from bench.generators import suite
from weaveengine.plan.context import Options
from weaveengine.router import route_board
from weaveengine.topo import planar_map
from weaveengine.topo.costs import CostParams

CONFIGS = {
    "full": Options(),
    "E1 greedy shortest-first": Options(global_selection=False, regret_order=False, lookahead=False, demand=False, ripup=False),
    "E1 regret order only": Options(global_selection=True, lookahead=False, demand=False, ripup=False),
    "E2 no global selection": Options(global_selection=False),
    "E3 no airwire/closure": Options(lookahead=False),
    "E4 no demand map": Options(demand=False),
    "E5 no rip-up": Options(ripup=False),
    "no refinement (Phase 4)": Options(refine=False),
}


def run(board, options: Options, **param_overrides) -> dict:
    params = CostParams.for_map(planar_map.build(board), **param_overrides) if param_overrides else None
    result = route_board(board, params, options)
    stats = dict(result.stats)
    # Peak resident set size of the process so far (bytes on macOS, kilobytes on Linux).
    rss = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    stats["peak_mb"] = rss / (1e6 if sys.platform == "darwin" else 1e3)
    stats["drc"] = len(result.violations)
    return stats


def row(name: str, config: str, s: dict) -> str:
    return (f"| {name} | {config} | {s['routed']}/{s['connections']} | {100 * s['completion']:.0f}% | {s['vias']} | "
            f"{s['length_ratio']:.3f} | {s['ripup_rounds']} | {s['time_total']:.2f} | {s['peak_mb']:.0f} |")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--experiments", action="store_true")
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--only", help="substring filter on board names")
    args = ap.parse_args()

    lines = ["| board | config | routed | completion | vias | length ratio | rip-up rounds | time (s) | peak RSS (MB) |",
             "|---|---|---|---|---|---|---|---|---|"]
    print("\n".join(lines))
    configs = CONFIGS if args.experiments else {"full": CONFIGS["full"]}
    for name, board in suite().items():
        if args.only and args.only not in name:
            continue
        for config, options in configs.items():
            line = row(name, config, run(board, options))
            print(line, flush=True)
            lines.append(line)
        if args.experiments:
            for k in (1, 3, 10):
                line = row(name, f"E5 K={k}", run(board, Options(), K=k))
                print(line, flush=True)
                lines.append(line)
    if args.write:
        header = ("# Benchmark results\n\nGenerated by `python -m bench.run" + (" --experiments" if args.experiments else "")
                  + " --write`. Completion counts only connections that are routed with zero DRC violations.\n\n")
        Path(__file__).with_name("results.md").write_text(header + "\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
